// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity job-openings`. Do not edit by hand.
// Customizations belong in (none — this is a pure barrel).
// ============================================================================

export { JobOpeningsModule } from './job-openings.module';
export { JobOpeningsService } from './job-openings.service';
