import { Module } from '@nestjs/common';
import { EntityEngineModule } from '@packages/entity-engine';
import { JOB_OPENINGS_CONFIG } from './job-openings.config';
import { JobOpeningsController } from './job-openings.controller';
import { JobOpeningsService } from './job-openings.service';

// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity job-openings`. Do not edit by hand.
// Customizations belong in job-openings.service.ts (composition) or job-openings.controller.ts (routes).
// ============================================================================

@Module({
  imports: [EntityEngineModule.forEntity(JOB_OPENINGS_CONFIG)],
  controllers: [JobOpeningsController],
  providers: [JobOpeningsService],
  exports: [JobOpeningsService],
})
export class JobOpeningsModule {}
