import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import { z } from 'zod';
import { jobOpenings } from './schema/job-openings';

// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity job-openings`. Do not edit by hand.
// Customizations belong in job-openings.dto.ts.
// ============================================================================

export const GeneratedJobOpeningRowSchema = createSelectSchema(jobOpenings);

const RowFields = createInsertSchema(jobOpenings).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
  deletedBy: true,
  createdBy: true,
});

const FeatureFields = z.object({
  requiredSkills: z.array(z.string().uuid()).optional(),
  assignedRecruiters: z.array(z.string().uuid()).optional(),
});

export const GeneratedCreateJobOpeningSchema = RowFields.merge(FeatureFields);
export const GeneratedUpdateJobOpeningSchema = GeneratedCreateJobOpeningSchema.partial();
