export { RbacModule } from './rbac.module';
export { RbacService } from './services/rbac.service';
export { UserRolesRelationHandler } from './relation-handlers/user-roles-relation-handler';
export { PermissionRegistryService } from './services/permission-registry.service';
export { RbacGuard } from './guards/rbac.guard';
export { RequirePermission } from './decorators/require-permission.decorator';
export { RBAC_PERMISSIONS } from './permissions';
export { FieldPermissionsController } from './controllers/field-permissions.controller';
export type { Role, RoleMember, RoleWithSystem, PermissionRegistryEntry, PermissionScope, ScopedPermissions, BooleanPermissions, FieldPermissionEntityResolver } from './types';
export { FIELD_PERMISSION_ENTITY_RESOLVER } from './types';
export { roles, rolePermissions, userRoles } from './schema';
