export { RbacModule } from './rbac.module';
export { RbacService } from './services/rbac.service';
export { RbacGuard } from './guards/rbac.guard';
export { RequirePermission } from './decorators/require-permission.decorator';
export { AccessContext } from './decorators/access-context.decorator';
export { buildAccessContext } from './scope-context';
export type { AccessScopeSpec, DataAccessContext } from './scope-context';
export { RBAC_PERMISSIONS } from './permissions';
export { FieldPermissionsController } from './controllers/field-permissions.controller';
export type { Role, RoleMember, RoleOption, RoleWithSystem, PermissionScope, ScopedPermissions, BooleanPermissions, ScopeSpec, BuiltInScopeType, FieldPermissionEntityResolver } from './types';
export { BUILT_IN_SCOPE_TYPES, FIELD_PERMISSION_ENTITY_RESOLVER } from './types';
export { registerCustomScopeType, isKnownScopeType, listCustomScopeTypes, normaliseScopes } from './scope-types';
export { roles, rolePermissions, rolePermissionScopes, userRoles } from './schema';
export { ScopeResolverRegistry } from './scope-resolver';
export type { ScopeResolver, ScopeResolverContext, ScopeAnchorMap } from './scope-resolver';
export { DataAccessScopeService } from './data-access-scope.service';
export type { BuildScopePredicateOptions, InlineScopeResolver } from './data-access-scope.service';
export { OwnScopeResolver } from './scope-resolvers/own.resolver';
export { AssignedScopeResolver } from './scope-resolvers/assigned.resolver';
export { PermissionManifestRegistry } from './permission-manifest';
export type { PermissionManifest } from './permission-manifest';
export { RbacIntegrationModule } from './integration/rbac-integration.module';
export type { RbacFeatureConfig } from './integration/rbac-integration.module';
export { crudPermissionManifests } from './crud-permission-manifests';
export type { CrudPermissionManifestOptions } from './crud-permission-manifests';
