import type { ClientRow } from '../clients/types';
import { MOCK_HANDLERS } from './mockData';

// Demo fixture for the clients list — used by the design preview surface
// at `/console-preview*`. Real screens fetch from `useClientsList`.

export const CLIENTS_TODAY = '2026-04-15';

export const MOCK_CLIENT_ROWS: ClientRow[] = [
  {
    id: 'c1',
    name: 'Aarav Industries',
    legalName: 'Aarav Industries Pvt. Ltd.',
    taxIdentifier: '27AABCA1234H1Z5',
    initials: 'AI',
    color: 'hsl(218 56% 24%)',
    status: 'active',
    risk: 'at-risk',
    registeredLaws: 5,
    openFilings: 8,
    overdueFilings: 2,
    onTimePct: 84,
    primaryHandler: MOCK_HANDLERS[0],
    primaryContactEmail: 'finance@aaravindustries.in',
    onboardedDate: '2024-03-15',
    lastFilingDate: '2026-04-10',
  },
  {
    id: 'c2',
    name: 'Bluewave Exports',
    legalName: 'Bluewave Exports LLP',
    taxIdentifier: '29BAAAB5678G1Z9',
    initials: 'BE',
    color: 'hsl(140 31% 33%)',
    status: 'active',
    risk: 'healthy',
    registeredLaws: 4,
    openFilings: 5,
    overdueFilings: 0,
    onTimePct: 97,
    primaryHandler: MOCK_HANDLERS[1],
    primaryContactEmail: 'compliance@bluewave.co.in',
    onboardedDate: '2023-07-01',
    lastFilingDate: '2026-04-12',
  },
  {
    id: 'c3',
    name: 'Cedar Retail',
    legalName: 'Cedar Retail Stores Ltd.',
    taxIdentifier: '07CCCCC9012F1Z1',
    initials: 'CR',
    color: 'hsl(19 75% 44%)',
    status: 'active',
    risk: 'at-risk',
    registeredLaws: 4,
    openFilings: 6,
    overdueFilings: 1,
    onTimePct: 88,
    primaryHandler: MOCK_HANDLERS[2],
    primaryContactEmail: 'accounts@cedarretail.com',
    onboardedDate: '2024-01-10',
    lastFilingDate: '2026-04-08',
  },
  {
    id: 'c4',
    name: 'Drift Media',
    legalName: 'Drift Media Holdings',
    taxIdentifier: '33DDDDD3456E1Z3',
    initials: 'DM',
    color: 'hsl(42 62% 45%)',
    status: 'active',
    risk: 'healthy',
    registeredLaws: 3,
    openFilings: 4,
    overdueFilings: 0,
    onTimePct: 95,
    primaryHandler: MOCK_HANDLERS[3],
    primaryContactEmail: 'legal@driftmedia.in',
    onboardedDate: '2024-06-20',
    lastFilingDate: '2026-04-11',
  },
  {
    id: 'c5',
    name: 'Evergreen Labs',
    legalName: 'Evergreen Biological Labs',
    taxIdentifier: '36EEEEE7890D1Z5',
    initials: 'EL',
    color: 'hsl(218 40% 40%)',
    status: 'active',
    risk: 'critical',
    registeredLaws: 4,
    openFilings: 7,
    overdueFilings: 3,
    onTimePct: 76,
    primaryHandler: MOCK_HANDLERS[0],
    primaryContactEmail: 'cfo@evergreenlabs.co.in',
    onboardedDate: '2023-11-05',
    lastFilingDate: '2026-04-06',
  },
  {
    id: 'c6',
    name: 'Fable Studios',
    legalName: 'Fable Studios Pvt. Ltd.',
    taxIdentifier: '24FFFFF2345C1Z7',
    initials: 'FS',
    color: 'hsl(215 25% 35%)',
    status: 'active',
    risk: 'healthy',
    registeredLaws: 3,
    openFilings: 3,
    overdueFilings: 0,
    onTimePct: 100,
    primaryHandler: MOCK_HANDLERS[2],
    primaryContactEmail: 'ops@fablestudios.in',
    onboardedDate: '2025-01-12',
    lastFilingDate: '2026-04-14',
  },
  {
    id: 'c7',
    name: 'Greenfield Agri',
    legalName: 'Greenfield Agricultural Co.',
    taxIdentifier: '06GGGGG6789B1Z2',
    initials: 'GA',
    color: 'hsl(145 42% 30%)',
    status: 'onboarding',
    risk: 'healthy',
    registeredLaws: 2,
    openFilings: 0,
    overdueFilings: 0,
    onTimePct: 0,
    primaryHandler: MOCK_HANDLERS[1],
    primaryContactEmail: 'admin@greenfieldagri.in',
    onboardedDate: '2026-04-01',
    lastFilingDate: '',
  },
  {
    id: 'c8',
    name: 'Horizon Pharma',
    legalName: 'Horizon Pharmaceuticals Ltd.',
    taxIdentifier: '27HHHHH1234A1Z8',
    initials: 'HP',
    color: 'hsl(260 30% 38%)',
    status: 'active',
    risk: 'healthy',
    registeredLaws: 5,
    openFilings: 6,
    overdueFilings: 0,
    onTimePct: 93,
    primaryHandler: MOCK_HANDLERS[3],
    primaryContactEmail: 'compliance@horizonpharma.co.in',
    onboardedDate: '2023-04-18',
    lastFilingDate: '2026-04-13',
  },
  {
    id: 'c9',
    name: 'Indigo Logistics',
    legalName: 'Indigo Logistics & Supply Chain Pvt. Ltd.',
    taxIdentifier: '32IIIII5678C1Z4',
    initials: 'IL',
    color: 'hsl(210 48% 28%)',
    status: 'active',
    risk: 'at-risk',
    registeredLaws: 4,
    openFilings: 5,
    overdueFilings: 1,
    onTimePct: 86,
    primaryHandler: MOCK_HANDLERS[0],
    primaryContactEmail: 'tax@indigologistics.in',
    onboardedDate: '2024-09-10',
    lastFilingDate: '2026-04-09',
  },
  {
    id: 'c10',
    name: 'Jade Constructions',
    legalName: 'Jade Constructions & Infra Ltd.',
    taxIdentifier: '27JJJJJ9012D1Z6',
    initials: 'JC',
    color: 'hsl(175 35% 32%)',
    status: 'dormant',
    risk: 'healthy',
    registeredLaws: 3,
    openFilings: 0,
    overdueFilings: 0,
    onTimePct: 91,
    primaryHandler: MOCK_HANDLERS[2],
    primaryContactEmail: 'cfo@jadeconstruction.in',
    onboardedDate: '2023-08-22',
    lastFilingDate: '2025-12-18',
  },
  {
    id: 'c11',
    name: 'Kite Finserv',
    legalName: 'Kite Financial Services Pvt. Ltd.',
    taxIdentifier: '29KKKKK3456E1Z0',
    initials: 'KF',
    color: 'hsl(200 55% 30%)',
    status: 'active',
    risk: 'healthy',
    registeredLaws: 5,
    openFilings: 4,
    overdueFilings: 0,
    onTimePct: 98,
    primaryHandler: MOCK_HANDLERS[1],
    primaryContactEmail: 'regulatory@kitefinserv.com',
    onboardedDate: '2024-02-14',
    lastFilingDate: '2026-04-14',
  },
  {
    id: 'c12',
    name: 'Lumen Tech',
    legalName: 'Lumen Technologies India Pvt. Ltd.',
    taxIdentifier: '36LLLLL7890F1Z2',
    initials: 'LT',
    color: 'hsl(230 38% 36%)',
    status: 'active',
    risk: 'critical',
    registeredLaws: 4,
    openFilings: 9,
    overdueFilings: 4,
    onTimePct: 72,
    primaryHandler: MOCK_HANDLERS[3],
    primaryContactEmail: 'finance@lumentech.in',
    onboardedDate: '2024-05-30',
    lastFilingDate: '2026-04-05',
  },
];

export const CLIENT_STATUS_COUNTS = {
  active: MOCK_CLIENT_ROWS.filter((c) => c.status === 'active').length,
  onboarding: MOCK_CLIENT_ROWS.filter((c) => c.status === 'onboarding').length,
  dormant: MOCK_CLIENT_ROWS.filter((c) => c.status === 'dormant').length,
};

export const CLIENT_RISK_COUNTS = {
  healthy: MOCK_CLIENT_ROWS.filter((c) => c.status === 'active' && c.risk === 'healthy').length,
  'at-risk': MOCK_CLIENT_ROWS.filter((c) => c.status === 'active' && c.risk === 'at-risk').length,
  critical: MOCK_CLIENT_ROWS.filter((c) => c.status === 'active' && c.risk === 'critical').length,
};
