import type { ComplianceRule } from '../compliance-rules/types';
import { MOCK_HANDLERS } from './mockData';

// Demo fixture for the compliance rules registry — used only by the
// design preview surface. Real screens fetch via `useComplianceRulesList`.

export const COMPLIANCE_RULES_TODAY = '2026-04-15';
export const MOCK_COMPLIANCE_RULES: ComplianceRule[] = [
  {
    id: 'o1',
    code: 'GSTR-1',
    name: 'Outward supplies return',
    description: 'Invoice-level details of outward supplies filed monthly by regular taxpayers',
    lawGroup: 'gst',
    lawCode: 'GST',
    lawName: 'Goods & Services Tax',
    jurisdiction: 'central',
    frequency: 'monthly',
    applicableClients: 38,
    filingsThisPeriod: 38,
    onTimePct: 96,
    status: 'active',
    owner: MOCK_HANDLERS[0],
    lastReviewed: '2026-02-18',
  },
  {
    id: 'o2',
    code: 'GSTR-3B',
    name: 'Summary return',
    description: 'Self-declared summary return capturing liability and ITC for the tax period',
    lawGroup: 'gst',
    lawCode: 'GST',
    lawName: 'Goods & Services Tax',
    jurisdiction: 'central',
    frequency: 'monthly',
    applicableClients: 42,
    filingsThisPeriod: 42,
    onTimePct: 91,
    status: 'active',
    owner: MOCK_HANDLERS[0],
    lastReviewed: '2026-03-04',
  },
  {
    id: 'o3',
    code: 'GSTR-9',
    name: 'Annual return',
    description: 'Consolidated annual return required for registered taxpayers above turnover threshold',
    lawGroup: 'gst',
    lawCode: 'GST',
    lawName: 'Goods & Services Tax',
    jurisdiction: 'central',
    frequency: 'yearly',
    applicableClients: 24,
    filingsThisPeriod: 0,
    onTimePct: 88,
    status: 'active',
    owner: MOCK_HANDLERS[0],
    lastReviewed: '2026-01-12',
  },
  {
    id: 'o4',
    code: 'GSTR-9C',
    name: 'Reconciliation statement',
    description: 'Audit reconciliation between filed GST returns and audited financial statements',
    lawGroup: 'gst',
    lawCode: 'GST',
    lawName: 'Goods & Services Tax',
    jurisdiction: 'central',
    frequency: 'yearly',
    applicableClients: 11,
    filingsThisPeriod: 0,
    onTimePct: 82,
    status: 'active',
    owner: MOCK_HANDLERS[2],
    lastReviewed: '2026-01-12',
  },
  {
    id: 'o5',
    code: 'ITR-6',
    name: 'Income tax return — companies',
    description: 'Corporate income tax return for entities other than companies claiming exemption under section 11',
    lawGroup: 'itr',
    lawCode: 'IT',
    lawName: 'Income Tax Act',
    jurisdiction: 'central',
    frequency: 'yearly',
    applicableClients: 28,
    filingsThisPeriod: 0,
    onTimePct: 94,
    status: 'active',
    owner: MOCK_HANDLERS[3],
    lastReviewed: '2026-03-22',
  },
  {
    id: 'o6',
    code: 'ITR-7',
    name: 'Income tax return — trusts',
    description: 'Return for persons including companies required to furnish return under sections 139(4A) through 139(4F)',
    lawGroup: 'itr',
    lawCode: 'IT',
    lawName: 'Income Tax Act',
    jurisdiction: 'central',
    frequency: 'yearly',
    applicableClients: 4,
    filingsThisPeriod: 0,
    onTimePct: 100,
    status: 'active',
    owner: MOCK_HANDLERS[3],
    lastReviewed: '2026-03-22',
  },
  {
    id: 'o7',
    code: 'TDS-24Q',
    name: 'TDS return — salary',
    description: 'Quarterly statement of tax deducted at source on salary payments',
    lawGroup: 'tds',
    lawCode: 'TDS',
    lawName: 'Tax Deducted at Source',
    jurisdiction: 'central',
    frequency: 'quarterly',
    applicableClients: 36,
    filingsThisPeriod: 36,
    onTimePct: 93,
    status: 'active',
    owner: MOCK_HANDLERS[1],
    lastReviewed: '2026-02-28',
  },
  {
    id: 'o8',
    code: 'TDS-26Q',
    name: 'TDS return — non-salary',
    description: 'Quarterly statement of tax deducted at source on payments other than salary',
    lawGroup: 'tds',
    lawCode: 'TDS',
    lawName: 'Tax Deducted at Source',
    jurisdiction: 'central',
    frequency: 'quarterly',
    applicableClients: 31,
    filingsThisPeriod: 31,
    onTimePct: 89,
    status: 'active',
    owner: MOCK_HANDLERS[1],
    lastReviewed: '2026-02-28',
  },
  {
    id: 'o9',
    code: 'TDS-27Q',
    name: 'TDS return — non-resident',
    description: 'Quarterly statement of tax deducted on payments to non-residents',
    lawGroup: 'tds',
    lawCode: 'TDS',
    lawName: 'Tax Deducted at Source',
    jurisdiction: 'central',
    frequency: 'quarterly',
    applicableClients: 7,
    filingsThisPeriod: 7,
    onTimePct: 78,
    status: 'draft',
    owner: MOCK_HANDLERS[1],
    lastReviewed: '2026-04-02',
  },
  {
    id: 'o10',
    code: 'AOC-4',
    name: 'Financial statements filing',
    description: 'Annual filing of financial statements with the Registrar of Companies',
    lawGroup: 'roc',
    lawCode: 'ROC',
    lawName: 'Companies Act',
    jurisdiction: 'central',
    frequency: 'yearly',
    applicableClients: 26,
    filingsThisPeriod: 0,
    onTimePct: 87,
    status: 'active',
    owner: MOCK_HANDLERS[2],
    lastReviewed: '2026-01-30',
  },
  {
    id: 'o11',
    code: 'MGT-7',
    name: 'Annual return',
    description: 'Annual return disclosing shareholders, directors and capital structure of the company',
    lawGroup: 'roc',
    lawCode: 'ROC',
    lawName: 'Companies Act',
    jurisdiction: 'central',
    frequency: 'yearly',
    applicableClients: 26,
    filingsThisPeriod: 0,
    onTimePct: 85,
    status: 'active',
    owner: MOCK_HANDLERS[2],
    lastReviewed: '2026-01-30',
  },
  {
    id: 'o12',
    code: 'DIR-3 KYC',
    name: 'Director KYC',
    description: 'Annual KYC filing for every director holding a DIN as on 31 March',
    lawGroup: 'roc',
    lawCode: 'ROC',
    lawName: 'Companies Act',
    jurisdiction: 'central',
    frequency: 'yearly',
    applicableClients: 34,
    filingsThisPeriod: 0,
    onTimePct: 71,
    status: 'active',
    owner: MOCK_HANDLERS[2],
    lastReviewed: '2026-01-30',
  },
  {
    id: 'o13',
    code: 'PT-MH',
    name: 'Professional tax — Maharashtra',
    description: 'Monthly remittance of professional tax deducted from employees in Maharashtra',
    lawGroup: 'pt',
    lawCode: 'PT',
    lawName: 'Professional Tax (Maharashtra)',
    jurisdiction: 'state',
    frequency: 'monthly',
    applicableClients: 19,
    filingsThisPeriod: 19,
    onTimePct: 98,
    status: 'active',
    owner: MOCK_HANDLERS[1],
    lastReviewed: '2026-03-12',
  },
  {
    id: 'o14',
    code: 'EPF-ECR',
    name: 'EPF electronic challan',
    description: 'Monthly electronic challan-cum-return for provident fund contributions',
    lawGroup: 'pf',
    lawCode: 'EPF',
    lawName: 'Employees Provident Fund Act',
    jurisdiction: 'central',
    frequency: 'monthly',
    applicableClients: 27,
    filingsThisPeriod: 27,
    onTimePct: 95,
    status: 'active',
    owner: MOCK_HANDLERS[1],
    lastReviewed: '2026-02-04',
  },
  {
    id: 'o15',
    code: 'ESI-MC',
    name: 'ESI monthly contribution',
    description: 'Monthly employee state insurance contribution for covered establishments',
    lawGroup: 'pf',
    lawCode: 'ESI',
    lawName: 'Employees State Insurance Act',
    jurisdiction: 'central',
    frequency: 'monthly',
    applicableClients: 22,
    filingsThisPeriod: 22,
    onTimePct: 92,
    status: 'draft',
    owner: MOCK_HANDLERS[1],
    lastReviewed: '2026-04-08',
  },
];

export const COMPLIANCE_RULE_STATUS_COUNTS = {
  active: MOCK_COMPLIANCE_RULES.filter((o) => o.status === 'active').length,
  draft: MOCK_COMPLIANCE_RULES.filter((o) => o.status === 'draft').length,
  deprecated: MOCK_COMPLIANCE_RULES.filter((o) => o.status === 'deprecated').length,
};
