import type { Filing, Client, Law, Handler } from '../../../../types';
import type { HandlerWorkload } from '../../../../components/composites/HandlerWorkloadBar';
import type { MatrixCellState } from '../../../../components/composites/ClientLawMatrix';

// Static mock data for the design preview — hand-tuned so that every
// widget renders with a plausible, visually-interesting shape.

export const PREVIEW_TODAY = new Date(2026, 3, 14); // 14 April 2026

function daysFromToday(offset: number): string {
  const d = new Date(PREVIEW_TODAY);
  d.setDate(d.getDate() + offset);
  return d.toISOString();
}

export const MOCK_HANDLERS: Handler[] = [
  { id: 'h1', name: 'Priya Shankar', initials: 'PS', role: 'Senior · GST Desk' },
  { id: 'h2', name: 'Arjun Mehta', initials: 'AM', role: 'Associate · ITR' },
  { id: 'h3', name: 'Kavita Rao', initials: 'KR', role: 'Manager · Audit' },
  { id: 'h4', name: 'Deepak Iyer', initials: 'DI', role: 'Partner' },
];

export const MOCK_LAWS: Law[] = [
  {
    id: 'l1',
    code: 'GST',
    name: 'Goods & Services Tax',
    jurisdiction: 'central',
    issuingAuthority: 'CBIC',
    effectiveFrom: '2017-07-01',
  },
  {
    id: 'l2',
    code: 'ITR',
    name: 'Income Tax Return',
    jurisdiction: 'central',
    issuingAuthority: 'CBDT',
    effectiveFrom: '1961-04-01',
  },
  {
    id: 'l3',
    code: 'TDS',
    name: 'Tax Deducted at Source',
    jurisdiction: 'central',
    issuingAuthority: 'CBDT',
    effectiveFrom: '1961-04-01',
  },
  {
    id: 'l4',
    code: 'ROC',
    name: 'Registrar of Companies',
    jurisdiction: 'central',
    issuingAuthority: 'MCA',
    effectiveFrom: '2013-04-01',
  },
  {
    id: 'l5',
    code: 'PT',
    name: 'Professional Tax',
    jurisdiction: 'state',
    locality: 'Maharashtra',
    issuingAuthority: 'State Treasury',
    effectiveFrom: '1975-04-01',
  },
];

export const MOCK_CLIENTS: Client[] = [
  { id: 'c1', name: 'Aarav Industries', legalName: 'Aarav Industries Pvt. Ltd.', taxIdentifier: '27AABCA1234H1Z5', initials: 'AI', color: 'hsl(218 56% 24%)' },
  { id: 'c2', name: 'Bluewave Exports', legalName: 'Bluewave Exports LLP', taxIdentifier: '29BAAAB5678G1Z9', initials: 'BE', color: 'hsl(140 31% 33%)' },
  { id: 'c3', name: 'Cedar Retail', legalName: 'Cedar Retail Stores Ltd.', taxIdentifier: '07CCCCC9012F1Z1', initials: 'CR', color: 'hsl(19 75% 44%)' },
  { id: 'c4', name: 'Drift Media', legalName: 'Drift Media Holdings', taxIdentifier: '33DDDDD3456E1Z3', initials: 'DM', color: 'hsl(42 62% 45%)' },
  { id: 'c5', name: 'Evergreen Labs', legalName: 'Evergreen Biological Labs', taxIdentifier: '36EEEEE7890D1Z5', initials: 'EL', color: 'hsl(218 40% 40%)' },
  { id: 'c6', name: 'Fable Studios', legalName: 'Fable Studios Pvt. Ltd.', taxIdentifier: '24FFFFF2345C1Z7', initials: 'FS', color: 'hsl(215 25% 35%)' },
];

export const MOCK_FILINGS: Filing[] = [
  {
    id: 'f1',
    clientId: 'c1',
    clientName: 'Aarav Industries',
    lawId: 'l1',
    lawCode: 'GSTR-3B',
    ruleName: 'GSTR-3B Monthly Return',
    dueDate: daysFromToday(-3),
    periodLabel: 'Mar 2026',
    handler: MOCK_HANDLERS[0],
    jurisdiction: 'central',
    status: 'overdue',
  },
  {
    id: 'f2',
    clientId: 'c2',
    clientName: 'Bluewave Exports',
    lawId: 'l1',
    lawCode: 'GSTR-1',
    ruleName: 'GSTR-1 Outward Supplies',
    dueDate: daysFromToday(0),
    periodLabel: 'Mar 2026',
    handler: MOCK_HANDLERS[0],
    jurisdiction: 'central',
    status: 'due-today',
  },
  {
    id: 'f3',
    clientId: 'c3',
    clientName: 'Cedar Retail',
    lawId: 'l3',
    lawCode: 'TDS-26Q',
    ruleName: 'TDS Return 26Q',
    dueDate: daysFromToday(2),
    periodLabel: 'Q4 FY26',
    handler: MOCK_HANDLERS[1],
    jurisdiction: 'central',
    status: 'due-this-week',
  },
  {
    id: 'f4',
    clientId: 'c4',
    clientName: 'Drift Media',
    lawId: 'l1',
    lawCode: 'GSTR-3B',
    ruleName: 'GSTR-3B Monthly Return',
    dueDate: daysFromToday(-10),
    periodLabel: 'Mar 2026',
    handler: MOCK_HANDLERS[0],
    jurisdiction: 'central',
    status: 'filed',
  },
  {
    id: 'f5',
    clientId: 'c5',
    clientName: 'Evergreen Labs',
    lawId: 'l4',
    lawCode: 'ROC-AOC4',
    ruleName: 'AOC-4 Annual Filing',
    dueDate: daysFromToday(6),
    periodLabel: 'FY 2025-26',
    handler: MOCK_HANDLERS[2],
    jurisdiction: 'central',
    status: 'due-this-week',
  },
  {
    id: 'f6',
    clientId: 'c6',
    clientName: 'Fable Studios',
    lawId: 'l2',
    lawCode: 'ITR-6',
    ruleName: 'Income Tax Return — ITR-6',
    dueDate: daysFromToday(14),
    periodLabel: 'AY 2026-27',
    handler: MOCK_HANDLERS[3],
    jurisdiction: 'central',
    status: 'upcoming',
  },
  {
    id: 'f7',
    clientId: 'c2',
    clientName: 'Bluewave Exports',
    lawId: 'l5',
    lawCode: 'PT-STATE',
    ruleName: 'Professional Tax Return',
    dueDate: daysFromToday(-8),
    periodLabel: 'Mar 2026',
    handler: MOCK_HANDLERS[1],
    jurisdiction: 'state',
    status: 'filed',
  },
  {
    id: 'f8',
    clientId: 'c1',
    clientName: 'Aarav Industries',
    lawId: 'l3',
    lawCode: 'TDS-24Q',
    ruleName: 'TDS Return 24Q',
    dueDate: daysFromToday(4),
    periodLabel: 'Q4 FY26',
    handler: MOCK_HANDLERS[1],
    jurisdiction: 'central',
    status: 'due-this-week',
  },
  {
    id: 'f9',
    clientId: 'c3',
    clientName: 'Cedar Retail',
    lawId: 'l1',
    lawCode: 'GSTR-1',
    ruleName: 'GSTR-1 Outward Supplies',
    dueDate: daysFromToday(0),
    periodLabel: 'Mar 2026',
    handler: MOCK_HANDLERS[0],
    jurisdiction: 'central',
    status: 'due-today',
  },
  {
    id: 'f10',
    clientId: 'c4',
    clientName: 'Drift Media',
    lawId: 'l2',
    lawCode: 'ITR-6',
    ruleName: 'Income Tax Return — ITR-6',
    dueDate: daysFromToday(21),
    periodLabel: 'AY 2026-27',
    handler: MOCK_HANDLERS[3],
    jurisdiction: 'central',
    status: 'upcoming',
  },
  {
    id: 'f11',
    clientId: 'c5',
    clientName: 'Evergreen Labs',
    lawId: 'l1',
    lawCode: 'GSTR-3B',
    ruleName: 'GSTR-3B Monthly Return',
    dueDate: daysFromToday(1),
    periodLabel: 'Mar 2026',
    handler: MOCK_HANDLERS[0],
    jurisdiction: 'central',
    status: 'due-this-week',
  },
  {
    id: 'f12',
    clientId: 'c6',
    clientName: 'Fable Studios',
    lawId: 'l4',
    lawCode: 'ROC-MGT7',
    ruleName: 'MGT-7 Annual Return',
    dueDate: daysFromToday(-1),
    periodLabel: 'FY 2025-26',
    handler: MOCK_HANDLERS[2],
    jurisdiction: 'central',
    status: 'overdue',
  },
  {
    id: 'f13',
    clientId: 'c1',
    clientName: 'Aarav Industries',
    lawId: 'l5',
    lawCode: 'PT-STATE',
    ruleName: 'Professional Tax Return',
    dueDate: daysFromToday(9),
    periodLabel: 'Mar 2026',
    handler: MOCK_HANDLERS[1],
    jurisdiction: 'state',
    status: 'upcoming',
  },
  {
    id: 'f14',
    clientId: 'c2',
    clientName: 'Bluewave Exports',
    lawId: 'l2',
    lawCode: 'ITR-6',
    ruleName: 'Income Tax Return — ITR-6',
    dueDate: daysFromToday(18),
    periodLabel: 'AY 2026-27',
    handler: MOCK_HANDLERS[3],
    jurisdiction: 'central',
    status: 'upcoming',
  },
  {
    id: 'f15',
    clientId: 'c3',
    clientName: 'Cedar Retail',
    lawId: 'l4',
    lawCode: 'ROC-AOC4',
    ruleName: 'AOC-4 Annual Filing',
    dueDate: daysFromToday(12),
    periodLabel: 'FY 2025-26',
    handler: MOCK_HANDLERS[2],
    jurisdiction: 'central',
    status: 'upcoming',
  },
];

export const MOCK_WORKLOADS: HandlerWorkload[] = [
  { handler: MOCK_HANDLERS[0], overdue: 3, dueThisWeek: 11, upcoming: 8 },
  { handler: MOCK_HANDLERS[1], overdue: 1, dueThisWeek: 7, upcoming: 12 },
  { handler: MOCK_HANDLERS[2], overdue: 2, dueThisWeek: 4, upcoming: 9 },
  { handler: MOCK_HANDLERS[3], overdue: 0, dueThisWeek: 2, upcoming: 6 },
];

export const MOCK_MATRIX_CELLS: Record<string, Record<string, { state: MatrixCellState; period?: string }>> = {
  c1: {
    l1: { state: 'overdue', period: 'Mar 26' },
    l2: { state: 'upcoming', period: 'AY 27' },
    l3: { state: 'due-this-week', period: 'Q4' },
    l4: { state: 'filed', period: 'FY 26' },
    l5: { state: 'upcoming', period: 'Mar 26' },
  },
  c2: {
    l1: { state: 'due-this-week', period: 'Mar 26' },
    l2: { state: 'upcoming', period: 'AY 27' },
    l3: { state: 'filed', period: 'Q4' },
    l4: { state: 'none' },
    l5: { state: 'filed', period: 'Mar 26' },
  },
  c3: {
    l1: { state: 'due-this-week', period: 'Mar 26' },
    l2: { state: 'upcoming', period: 'AY 27' },
    l3: { state: 'due-this-week', period: 'Q4' },
    l4: { state: 'upcoming', period: 'FY 26' },
    l5: { state: 'none' },
  },
  c4: {
    l1: { state: 'filed', period: 'Mar 26' },
    l2: { state: 'upcoming', period: 'AY 27' },
    l3: { state: 'upcoming', period: 'Q4' },
    l4: { state: 'none' },
    l5: { state: 'none' },
  },
  c5: {
    l1: { state: 'due-this-week', period: 'Mar 26' },
    l2: { state: 'upcoming', period: 'AY 27' },
    l3: { state: 'pending', period: 'Q4' },
    l4: { state: 'due-this-week', period: 'FY 26' },
    l5: { state: 'none' },
  },
  c6: {
    l1: { state: 'upcoming', period: 'Mar 26' },
    l2: { state: 'upcoming', period: 'AY 27' },
    l3: { state: 'pending', period: 'Q4' },
    l4: { state: 'overdue', period: 'FY 26' },
    l5: { state: 'none' },
  },
};

export const MOCK_GST_HIERARCHY = [
  {
    id: 'gst',
    label: 'Goods & Services Tax',
    code: 'GST',
    meta: '12 rules',
    defaultOpen: true,
    children: [
      {
        id: 'gst-returns',
        label: 'Returns',
        code: 'GST/R',
        meta: '6 rules',
        defaultOpen: true,
        children: [
          { id: 'gstr-1', label: 'GSTR-1 · Outward supplies', code: 'GSTR-1', meta: 'Monthly' },
          { id: 'gstr-3b', label: 'GSTR-3B · Summary return', code: 'GSTR-3B', meta: 'Monthly' },
          { id: 'gstr-9', label: 'GSTR-9 · Annual return', code: 'GSTR-9', meta: 'Yearly' },
          { id: 'gstr-9c', label: 'GSTR-9C · Reconciliation', code: 'GSTR-9C', meta: 'Yearly' },
        ],
      },
      {
        id: 'gst-refunds',
        label: 'Refunds',
        code: 'GST/F',
        meta: '3 rules',
        children: [
          { id: 'rfd-01', label: 'RFD-01 · Refund application', code: 'RFD-01', meta: 'Ad-hoc' },
          { id: 'rfd-11', label: 'RFD-11 · LUT for exports', code: 'RFD-11', meta: 'Yearly' },
        ],
      },
      {
        id: 'gst-eway',
        label: 'E-Way Bills',
        code: 'GST/E',
        meta: '2 rules',
      },
    ],
  },
  {
    id: 'itr',
    label: 'Income Tax',
    code: 'ITR',
    meta: '8 rules',
    children: [
      {
        id: 'itr-returns',
        label: 'Returns',
        code: 'ITR/R',
        meta: '4 rules',
        children: [
          { id: 'itr-6', label: 'ITR-6 · Companies', code: 'ITR-6', meta: 'Yearly' },
          { id: 'itr-7', label: 'ITR-7 · Trusts', code: 'ITR-7', meta: 'Yearly' },
        ],
      },
      {
        id: 'tds',
        label: 'TDS Returns',
        code: 'TDS',
        meta: '4 rules',
        children: [
          { id: 'tds-24q', label: '24Q · Salary TDS', code: 'TDS-24Q', meta: 'Quarterly' },
          { id: 'tds-26q', label: '26Q · Non-salary TDS', code: 'TDS-26Q', meta: 'Quarterly' },
        ],
      },
    ],
  },
];
