import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import { z } from 'zod';
import { candidates } from './schema/candidates';

// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity candidates`. Do not edit by hand.
// Custom validation rules go in `candidates.dto.ts`.
// ============================================================================

export const GeneratedCandidateRowSchema = createSelectSchema(candidates);

const RowFields = createInsertSchema(candidates, {
  email: (s) => s.email().max(160),
  secondaryEmail: (s) => s.email().max(160).optional(),
  website: (s) => s.url().optional(),
  linkedinUrl: (s) => s.url().optional(),
  facebookUrl: (s) => s.url().optional(),
}).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
  deletedBy: true,
  createdBy: true,
});

// Cross-cutting feature fields declared in candidates.config.ts fieldMeta.
// These are stripped from the row payload by the service and routed to their
// owning subsystems (tags → taxonomy, etc.) inside the same transaction.
const FeatureFields = z.object({
  skills: z.array(z.string().uuid()).optional(),
});

export const GeneratedCreateCandidateSchema = RowFields.merge(FeatureFields);
export const GeneratedUpdateCandidateSchema = GeneratedCreateCandidateSchema.partial();
