import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import { z } from 'zod';
import { candidates } from './schema/candidates';

// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity candidates`. Do not edit by hand.
// Customizations belong in candidates.dto.ts.
// ============================================================================

export const GeneratedCandidateRowSchema = createSelectSchema(candidates);

const RowFields = createInsertSchema(candidates).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
  deletedBy: true,
  createdBy: true,
});

const FeatureFields = z.object({
  skills: z.array(z.string().uuid()).optional(),
});

export const GeneratedCreateCandidateSchema = RowFields.merge(FeatureFields);
export const GeneratedUpdateCandidateSchema = GeneratedCreateCandidateSchema.partial();
