import { Module } from '@nestjs/common';
import { EntityEngineModule } from '@packages/entity-engine';
import { candidatesConfig } from './candidates.config';
import { CandidatesController } from './candidates.controller';
import { CandidatesService } from './candidates.service';

// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity candidates`. Do not edit by hand.
// Customizations belong in candidates.service.ts (composition) or candidates.controller.ts (routes).
// ============================================================================

@Module({
  imports: [EntityEngineModule.forEntity(candidatesConfig)],
  controllers: [CandidatesController],
  providers: [CandidatesService],
  exports: [CandidatesService],
})
export class CandidatesModule {}
