// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity candidates`. Do not edit by hand.
// Customizations belong in (none — this is a pure barrel).
// ============================================================================

export { CandidatesModule } from './candidates.module';
export { CandidatesService } from './candidates.service';
