import path from 'node:path';
import fs from 'node:fs';
import { NestFactory } from '@nestjs/core';
import {
  EntityRegistryService,
  generateJsonbIndexes,
  type JsonbIndexStatement,
} from '@packages/entity-engine';
import { AppModule } from '../app.module';

function parseOutPath(argv: string[]): string | null {
  const outArg = argv.find((a) => a.startsWith('--out='));
  return outArg?.split('=')[1] ?? null;
}

function formatMigration(statements: JsonbIndexStatement[]): string {
  const header = `-- JSONB custom-field expression indexes
-- Generated by \`pnpm db:gen:jsonb-indexes\`. Safe to re-run: every statement uses
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS. Run each statement outside a transaction
-- so CONCURRENTLY can take effect.

`;
  if (statements.length === 0) {
    return header + '-- No fieldMeta entries marked { indexed: true } yet.\n';
  }
  const grouped = statements.reduce<Record<string, JsonbIndexStatement[]>>((acc, s) => {
    (acc[s.entityType] ??= []).push(s);
    return acc;
  }, {});

  const body = Object.entries(grouped)
    .map(([entityType, stmts]) => {
      const lines = stmts.map((s) => s.sql).join('\n');
      return `-- ${entityType}\n${lines}`;
    })
    .join('\n\n');

  return header + body + '\n';
}

async function main() {
  const outPath = parseOutPath(process.argv.slice(2));

  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: ['error', 'warn'],
  });

  try {
    const registry = app.get(EntityRegistryService);
    const statements = generateJsonbIndexes(registry.getAll());
    const sql = formatMigration(statements);

    if (outPath) {
      const absolute = path.resolve(process.cwd(), outPath);
      fs.mkdirSync(path.dirname(absolute), { recursive: true });
      fs.writeFileSync(absolute, sql, 'utf8');
      console.log(`[db:gen:jsonb-indexes] wrote ${statements.length} statement(s) to ${absolute}`);
    } else {
      process.stdout.write(sql);
    }
  } finally {
    await app.close();
  }
}

main().catch((err) => {
  console.error('[db:gen:jsonb-indexes] failed:', err);
  process.exit(1);
});
