import { z } from 'zod';
import { fieldTypeRegistry } from '@packages/field-types';
import { fieldTypeUIRegistry } from '@packages/field-types/ui';
import type { FieldDefinition } from '../types';

/**
 * Build a Zod schema dynamically from field definitions.
 * Uses the field type UI registry to get the correct schema per type.
 */
export function buildFormSchema(fields: FieldDefinition[]): z.ZodObject<Record<string, z.ZodTypeAny>> {
  const shape: Record<string, z.ZodTypeAny> = {};

  for (const field of fields) {
    const ft = fieldTypeRegistry.get(field.fieldType);
    const uiDef = fieldTypeUIRegistry.get(field.fieldType);

    // Skip non-editable fields
    if (ft?.autoGenerated || field.isReadonly) continue;

    let fieldSchema: z.ZodTypeAny;

    if (uiDef) {
      fieldSchema = uiDef.zodSchema({ maxLength: field.maxLength });
    } else {
      fieldSchema = z.string();
    }

    // Make optional if not required
    if (!field.isRequired) {
      if (field.fieldType === 'boolean' || ft?.isArray) {
        fieldSchema = fieldSchema.optional();
      } else {
        fieldSchema = z.union([fieldSchema, z.literal('')]).optional();
      }
    }

    shape[field.fieldKey] = fieldSchema;
  }

  return z.object(shape);
}
