export { RbacModule } from './rbac.module';
export { RbacService } from './services/rbac.service';
export { PermissionRegistryService } from './services/permission-registry.service';
export { RbacGuard } from './guards/rbac.guard';
export { RequirePermission } from './decorators/require-permission.decorator';
export { RBAC_PERMISSIONS } from './permissions';
export { FieldPermissionsController } from './controllers/field-permissions.controller';
export type { Role, RoleWithSystem, PermissionRegistryEntry, PermissionScope, ScopedPermissions, FieldPermissionEntityResolver } from './types';
export { FIELD_PERMISSION_ENTITY_RESOLVER } from './types';
export { roles, rolePermissions, userRoles } from './schema';
export { scopeFilter, extractCustomScopeKey } from './helpers/scope-filter';
