// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity interviews`. Do not edit by hand.
// Customizations belong in (none — this is a pure barrel).
// ============================================================================

export { InterviewsModule } from './interviews.module';
export { InterviewsService } from './interviews.service';
