import { Module } from '@nestjs/common';
import { EntityEngineModule } from '@packages/entity-engine';
import { INTERVIEWS_CONFIG } from './interviews.config';
import { InterviewsController } from './interviews.controller';
import { InterviewsService } from './interviews.service';

// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity interviews`. Do not edit by hand.
// Customizations belong in interviews.service.ts (composition) or interviews.controller.ts (routes).
// ============================================================================

@Module({
  imports: [EntityEngineModule.forEntity(INTERVIEWS_CONFIG)],
  controllers: [InterviewsController],
  providers: [InterviewsService],
  exports: [InterviewsService],
})
export class InterviewsModule {}
