import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import { z } from 'zod';
import { interviews } from './schema/interviews';

// ============================================================================
// AUTO-GENERATED by `pnpm gen:entity interviews`. Do not edit by hand.
// Customizations belong in interviews.dto.ts.
// ============================================================================

export const GeneratedInterviewRowSchema = createSelectSchema(interviews);

const RowFields = createInsertSchema(interviews).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
  deletedBy: true,
  createdBy: true,
});

const FeatureFields = z.object({
  interviewers: z.array(z.string().uuid()).optional(),
});

export const GeneratedCreateInterviewSchema = RowFields.merge(FeatureFields);
export const GeneratedUpdateInterviewSchema = GeneratedCreateInterviewSchema.partial();
