import type { EntityUIConfig } from '@packages/entity-engine-ui';
import { searchCompaniesForClientPicker, resolveCompanyToClient } from './clientId-picker';

export const CONTACTS_UI_CONFIG: EntityUIConfig = {
  entityType: 'contacts',
  presentation: {
    singularName: 'Contact',
    pluralName: 'Contacts',
    subtitleField: 'jobTitle',
    icon: 'contact',
    navGroup: 'recruit',
    navOrder: 5,
  },
  fieldUI: {
    fullName: { label: 'Contact', cellRenderer: 'AvatarNameCell' },
    firstName: { label: 'First Name' },
    lastName: { label: 'Last Name' },
    clientId: {
      label: 'Client Name',
      lookupSearch: searchCompaniesForClientPicker,
      lookupResolveValue: resolveCompanyToClient,
    },
    department: { label: 'Department' },
    email: { label: 'Email' },
    secondaryEmail: { label: 'Secondary Email' },
    jobTitle: { label: 'Job Title' },
    workPhone: { label: 'Work Phone' },
    mobile: { label: 'Mobile' },
    mailingStreet: { label: 'Mailing Street' },
    mailingCity: { label: 'Mailing City' },
    mailingProvince: { label: 'Mailing Province' },
    mailingPostalCode: { label: 'Mailing Postal Code' },
    mailingCountry: { label: 'Mailing Country' },
    otherStreet: { label: 'Other Street' },
    otherCity: { label: 'Other City' },
    otherProvince: { label: 'Other Province' },
    otherPostalCode: { label: 'Other Postal Code' },
    otherCountry: { label: 'Other Country' },
    linkedinUrl: { label: 'LinkedIn' },
    facebookUrl: { label: 'Facebook' },
    twitterHandle: { label: 'Twitter' },
    source: { label: 'Source' },
    isPrimaryContact: { label: 'Is Primary Contact' },
    emailOptOut: { label: 'Email Opt Out' },
  },
  formLayout: {
    sections: [
      { name: 'Contact Information', fields: ['firstName', 'lastName', 'clientId', 'department', 'email', 'secondaryEmail', 'jobTitle', 'workPhone', 'mobile'] },
      { name: 'Mailing Address', fields: ['mailingStreet', 'mailingCity', 'mailingProvince', 'mailingPostalCode', 'mailingCountry'] },
      { name: 'Other Address', fields: ['otherStreet', 'otherCity', 'otherProvince', 'otherPostalCode', 'otherCountry'] },
      { name: 'Social Links', fields: ['linkedinUrl', 'facebookUrl', 'twitterHandle'] },
      { name: 'Other Info', fields: ['source', 'isPrimaryContact', 'emailOptOut'] },
    ],
    quickCreateFields: ['firstName', 'lastName', 'clientId', 'email', 'workPhone', 'mobile'],
  },
  listColumns: [
    { fieldKey: 'fullName', visible: true, order: 0 },
    { fieldKey: 'clientId', visible: true, order: 1 },
    { fieldKey: 'email', visible: true, order: 2 },
    { fieldKey: 'mobile', visible: true, order: 3 },
    { fieldKey: 'jobTitle', visible: true, order: 4 },
  ],
};
