import type { EntityUIConfig } from '@packages/entity-engine-ui';

export const JOB_OPENINGS_UI_CONFIG: EntityUIConfig = {
  entityType: 'job_openings',
  presentation: {
    singularName: 'Job Opening',
    pluralName: 'Job Openings',
    subtitleField: 'department',
    icon: 'briefcase',
    navGroup: 'recruit',
    navOrder: 1,
    createMode: 'page',
  },
  fieldUI: {
    title: { label: 'Posting Title' },
    clientId: { label: 'Client Name' },
    contactId: { label: 'Contact Name' },
    hiringManager: { label: 'Hiring Manager' },
    accountManager: { label: 'Account Manager' },
    assignedRecruiters: { label: 'Assigned Recruiter(s)' },
    dateOpened: { label: 'Date Opened' },
    targetDate: { label: 'Target Date' },
    employmentType: { label: 'Job Type' },
    status: { label: 'Job Opening Status', cellRenderer: 'StatusBadge' },
    experience: { label: 'Work Experience' },
    industry: { label: 'Industry' },
    jobFunction: { label: 'Job Function' },
    confidential: { label: 'Confidential' },
    requiredSkills: { label: 'Required Skills' },
    salaryMin: { label: 'Salary Min' },
    salaryMax: { label: 'Salary Max' },
    currency: { label: 'Currency' },
    department: { label: 'Department' },
    location: { label: 'Office' },
    country: { label: 'Country' },
    postalCode: { label: 'Postal Code' },
    remoteJob: { label: 'Remote Job' },
    numberOfPositions: { label: 'Number of Positions' },
    revenuePerPosition: { label: 'Revenue per Position' },
    jobDescription: { label: 'Job Description' },
    jobRequirements: { label: 'Requirements' },
    benefits: { label: 'Benefits' },
    jobSummary: { label: 'Job Summary' },
    otherAttachments: { label: 'Others' },
  },
  formLayout: {
    sections: [
      {
        name: 'Job Opening Information', columns: 2,
        fields: ['title', 'clientId', 'contactId', 'hiringManager', 'accountManager', 'assignedRecruiters', 'dateOpened', 'targetDate', 'employmentType', 'status', 'experience', 'industry', 'jobFunction', 'confidential', 'requiredSkills'],
      },
      {
        name: 'Address Information', columns: 2,
        fields: ['department', 'location', 'country', 'postalCode', 'remoteJob'],
      },
      {
        name: 'Compensation', columns: 2,
        fields: ['salaryMin', 'salaryMax', 'currency'],
      },
      {
        name: 'Forecast Details', columns: 2,
        fields: ['numberOfPositions', 'revenuePerPosition'],
      },
      {
        name: 'Description Information', columns: 1,
        fields: ['jobDescription', 'jobRequirements', 'benefits'],
      },
      {
        name: 'Attachment Information', columns: 1,
        fields: ['jobSummary', 'otherAttachments'],
      },
    ],
    quickCreateFields: ['title', 'clientId', 'assignedRecruiters', 'targetDate', 'requiredSkills'],
  },
  listColumns: [
    { fieldKey: 'title', visible: true, order: 0 },
    { fieldKey: 'clientId', visible: true, order: 1 },
    { fieldKey: 'status', visible: true, order: 2 },
    { fieldKey: 'targetDate', visible: true, order: 3 },
    { fieldKey: 'applicationsCount', visible: true, order: 4 },
  ],
  actionUI: {
    edit: { label: 'Edit', icon: 'Pencil' },
    clone: { label: 'Clone', icon: 'Copy' },
    delete: { label: 'Delete', icon: 'Trash2', variant: 'destructive' },
    massUpdate: { label: 'Mass Update', icon: 'PenLine' },
    massDelete: { label: 'Mass Delete', icon: 'Trash2', variant: 'destructive' },
    export: { label: 'Export', icon: 'Download' },
    'apply-candidate': { label: 'Apply Candidate', icon: 'UserPlus' },
  },
};
