import type { RuleTemplate } from './types';

// Platform-shipped catalog of standard regulatory rule templates.
// Firms instantiate (and optionally customise) a rule from one of
// these templates. Static today; eventually sourced from the API
// when the platform team updates them with regulatory changes.

export const RULE_TEMPLATES: RuleTemplate[] = [
  {
    id: 'tpl-1',
    code: 'GSTR-1',
    name: 'Outward supplies return',
    description: 'Invoice-level details of outward supplies filed monthly by regular taxpayers',
    lawGroup: 'gst',
    lawCode: 'GST',
    lawName: 'Goods & Services Tax',
    jurisdiction: 'central',
    frequency: 'monthly',
    dueDayOfMonth: 11,
    dueMonthOffset: 1,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-2',
    code: 'GSTR-3B',
    name: 'Summary return',
    description: 'Self-declared summary return capturing liability and ITC for the tax period',
    lawGroup: 'gst',
    lawCode: 'GST',
    lawName: 'Goods & Services Tax',
    jurisdiction: 'central',
    frequency: 'monthly',
    dueDayOfMonth: 20,
    dueMonthOffset: 1,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-3',
    code: 'GSTR-9',
    name: 'Annual return',
    description: 'Consolidated annual return required for registered taxpayers above turnover threshold',
    lawGroup: 'gst',
    lawCode: 'GST',
    lawName: 'Goods & Services Tax',
    jurisdiction: 'central',
    frequency: 'yearly',
    dueDayOfMonth: 31,
    dueMonthOffset: 9,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-4',
    code: 'GSTR-9C',
    name: 'Reconciliation statement',
    description: 'Audit reconciliation between filed GST returns and audited financial statements',
    lawGroup: 'gst',
    lawCode: 'GST',
    lawName: 'Goods & Services Tax',
    jurisdiction: 'central',
    frequency: 'yearly',
    dueDayOfMonth: 31,
    dueMonthOffset: 9,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-5',
    code: 'ITR-6',
    name: 'Income tax return — companies',
    description: 'Corporate income tax return for entities other than companies claiming exemption under section 11',
    lawGroup: 'itr',
    lawCode: 'IT',
    lawName: 'Income Tax Act',
    jurisdiction: 'central',
    frequency: 'yearly',
    dueDayOfMonth: 31,
    dueMonthOffset: 7,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-6',
    code: 'TDS-24Q',
    name: 'TDS return — salary',
    description: 'Quarterly statement of tax deducted at source on salary payments',
    lawGroup: 'tds',
    lawCode: 'TDS',
    lawName: 'Tax Deducted at Source',
    jurisdiction: 'central',
    frequency: 'quarterly',
    dueDayOfMonth: 31,
    dueMonthOffset: 1,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-7',
    code: 'TDS-26Q',
    name: 'TDS return — non-salary',
    description: 'Quarterly statement of tax deducted at source on payments other than salary',
    lawGroup: 'tds',
    lawCode: 'TDS',
    lawName: 'Tax Deducted at Source',
    jurisdiction: 'central',
    frequency: 'quarterly',
    dueDayOfMonth: 31,
    dueMonthOffset: 1,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-8',
    code: 'AOC-4',
    name: 'Financial statements filing',
    description: 'Annual filing of financial statements with the Registrar of Companies',
    lawGroup: 'roc',
    lawCode: 'ROC',
    lawName: 'Companies Act',
    jurisdiction: 'central',
    frequency: 'yearly',
    dueDayOfMonth: 30,
    dueMonthOffset: 6,
    gracePeriodDays: 30,
  },
  {
    id: 'tpl-9',
    code: 'MGT-7',
    name: 'Annual return',
    description: 'Annual return disclosing shareholders, directors and capital structure of the company',
    lawGroup: 'roc',
    lawCode: 'ROC',
    lawName: 'Companies Act',
    jurisdiction: 'central',
    frequency: 'yearly',
    dueDayOfMonth: 29,
    dueMonthOffset: 8,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-10',
    code: 'EPF-ECR',
    name: 'EPF electronic challan',
    description: 'Monthly electronic challan-cum-return for provident fund contributions',
    lawGroup: 'pf',
    lawCode: 'EPF',
    lawName: 'Employees Provident Fund Act',
    jurisdiction: 'central',
    frequency: 'monthly',
    dueDayOfMonth: 15,
    dueMonthOffset: 1,
    gracePeriodDays: 0,
  },
  {
    id: 'tpl-11',
    code: 'ESI-MC',
    name: 'ESI monthly contribution',
    description: 'Monthly employee state insurance contribution for covered establishments',
    lawGroup: 'pf',
    lawCode: 'ESI',
    lawName: 'Employees State Insurance Act',
    jurisdiction: 'central',
    frequency: 'monthly',
    dueDayOfMonth: 15,
    dueMonthOffset: 1,
    gracePeriodDays: 5,
  },
  {
    id: 'tpl-12',
    code: 'PT-MH',
    name: 'Professional tax — Maharashtra',
    description: 'Monthly remittance of professional tax deducted from employees in Maharashtra',
    lawGroup: 'pt',
    lawCode: 'PT',
    lawName: 'Professional Tax (Maharashtra)',
    jurisdiction: 'state',
    frequency: 'monthly',
    dueDayOfMonth: 30,
    dueMonthOffset: 0,
    gracePeriodDays: 0,
  },
];
