import { Module } from '@nestjs/common';
import { EntityEngineModule } from '@packages/entity-engine';
import { PAGES_CONFIG } from './pages.config';
import { SECTIONS_CONFIG } from './sections.config';

/**
 * PagesModule registers two entities with the entity-engine: `pages` (the
 * landing-page header/SEO shell) and `sections` (ordered children, JSONB
 * custom-field storage). CRUD controllers, permissions, audit events, field
 * definitions, list/filter/search are all auto-generated by the engine.
 *
 * Custom endpoints (public by-slug, bulk reorder) are added in a dedicated
 * controller in a follow-up task.
 */
@Module({
  imports: [
    EntityEngineModule.forEntity(PAGES_CONFIG),
    EntityEngineModule.forEntity(SECTIONS_CONFIG),
  ],
})
export class PagesModule {}
