import { Module, type OnModuleInit } from '@nestjs/common';
import { EntityEngineModule } from '@packages/entity-engine';
import { fieldTypeRegistry } from '@packages/field-types';
import { dataSourceFieldTypePlugin } from '@packages/blocks-contract';
import { PAGES_CONFIG } from './pages.config';
import { SECTIONS_CONFIG } from './sections.config';
import { PagesPublicController } from './controllers/pages-public.controller';
import { PagesPublicService } from './services/pages-public.service';

/**
 * PagesModule registers two entities with the entity-engine: `pages` (the
 * landing-page header/SEO shell) and `sections` (ordered children, JSONB
 * custom-field storage). CRUD controllers, permissions, audit events, field
 * definitions, list/filter/search are all auto-generated by the engine.
 *
 * Adds two non-generated endpoints:
 * - GET  /public/pages/:slug                — anonymous, read by slug
 * - PUT  /pages/:pageId/sections:reorder    — authenticated, bulk reorder
 *
 * Registers the `data_source` platform field type so `sections.dataSource`
 * flows through the generic CRUD pipeline (validate → write → read).
 */
@Module({
  imports: [
    EntityEngineModule.forEntity(PAGES_CONFIG),
    EntityEngineModule.forEntity(SECTIONS_CONFIG),
  ],
  controllers: [PagesPublicController],
  providers: [PagesPublicService],
  exports: [PagesPublicService],
})
export class PagesModule implements OnModuleInit {
  onModuleInit() {
    if (!fieldTypeRegistry.has('data_source')) {
      fieldTypeRegistry.registerPlugin(dataSourceFieldTypePlugin);
    }
  }
}
