import type { EntityUIConfig } from '@packages/entity-engine-ui';

export const COMPLIANCE_FILINGS_UI_CONFIG: EntityUIConfig = {
  entityType: 'compliance-filings',
  presentation: {
    singularName: 'Compliance Filing',
    pluralName: 'Compliance Filings',
    icon: 'ClipboardCheck',
    navGroup: 'compliance',
    navOrder: 4,
  },
  fieldUI: {
    title: { label: 'Title' },
    description: { label: 'Description' },
    status: { label: 'Status', cellRenderer: 'PipelineProgressRenderer' },
    priority: { label: 'Priority' },
    assigneeId: { label: 'Assignee' },
    assigneeTeamId: { label: 'Assigned Team', listColumnHidden: true },
    dueDate: { label: 'Due Date' },
    completedAt: { label: 'Completed At' },
    ruleId: { label: 'Rule' },
    clientId: { label: 'Client' },
    lawId: { label: 'Law' },
    periodStart: { label: 'Period Start' },
    periodEnd: { label: 'Period End' },
    externalKey: { label: 'External Key' },
    createdBy: { label: 'Creator' },
  },
  listColumns: [
    { fieldKey: 'title', visible: true, order: 1 },
    { fieldKey: 'status', visible: true, order: 2 },
    { fieldKey: 'priority', visible: true, order: 3 },
    { fieldKey: 'assigneeId', visible: true, order: 4 },
    { fieldKey: 'dueDate', visible: true, order: 5 },
    { fieldKey: 'ruleId', visible: true, order: 6 },
    { fieldKey: 'clientId', visible: true, order: 7 },
    { fieldKey: 'lawId', visible: true, order: 8 },
    { fieldKey: 'periodStart', visible: true, order: 9 },
    { fieldKey: 'periodEnd', visible: true, order: 10 },
  ],
};
