export type {
  TriggerType,
  ScheduleDateOperator,
  ScheduleUnit,
  UserSlotDefinition,
  UserResolutionStrategy,
  UserResolution,
  ActionConfig,
  ActionContext,
  ActionResult,
  ActionHandler,
  LifecycleUpdateBinding,
  LifecycleDeleteBinding,
  AutomationRule,
  AutomationActionLogEntry,
  AutomationExecutionEntry,
  EntityFieldType,
  EntityFieldConfig,
  ResolvedEntityFieldConfig,
  EntityUserFieldConfig,
  EntityResolverConfig,
} from '@packages/automation-contracts';
