import type { Config } from 'tailwindcss';
import baseConfig from '../../../../../packages/core/ui/tailwind.config';

const config: Config = {
  ...baseConfig,
  content: [
    './src/**/*.{ts,tsx}',
    './index.html',
    '../../../../../packages/core/debug-profiler/ui/*.{ts,tsx}',
    '../../../../../packages/core/ui/components/**/*.{ts,tsx}',
    '../../../../../packages/core/ui/hooks/**/*.{ts,tsx}',
    '../../../../../packages/core/ui/lib/**/*.{ts,tsx}',
    '../../../../../packages/core/ui/kit/**/*.{ts,tsx}',
    '../../../../../packages/platform/app-shell/ui/index.tsx',
    '../../../../../packages/platform/app-shell/ui/src/**/*.{ts,tsx}',
    '../../../../../packages/platform/entity-engine/ui/*.{ts,tsx}',
    '../../../../../packages/platform/entity-engine/ui/components/**/*.{ts,tsx}',
    '../../../../../packages/platform/entity-engine/ui/helpers/**/*.{ts,tsx}',
    '../../../../../packages/platform/entity-engine/ui/pages/**/*.{ts,tsx}',
    '../../../../../packages/platform/eav-attributes-ui/components/**/*.{ts,tsx}',
    '../../../../../packages/platform/eav-attributes-ui/field-types/**/*.{ts,tsx}',
    '../../../../../packages/platform/eav-attributes-ui/helpers/**/*.{ts,tsx}',
    '../../../../../packages/addons/entity-relations/ui/field-types/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/audit/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/conditions/*.tsx',
    '../../../../../packages/platform/notification-channels/ui/*.{ts,tsx}',
    '../../../../../packages/platform/notification-channels/ui/components/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/automations/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/notifications/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/rbac/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/settings/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/taxonomy/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/taxonomy/components/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/taxonomy/pages/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/users/**/*.{ts,tsx}',
    '../../../../../packages/platform/platform-ui/workflows/**/*.{ts,tsx}',
    '../../../../../packages/addons/pages/ui/admin/*.{ts,tsx}',
    '../../../../../domains/agency/ui/blocks/*.{ts,tsx}',
    '../../../../../domains/agency/ui/blocks/components/**/*.{ts,tsx}',
    '../../../../../packages/addons/menus/ui/admin/**/*.{ts,tsx}',
    '../../../../../packages/addons/menus/ui/frontend/**/*.{ts,tsx}',
    '../../../../../packages/addons/media-library/ui/admin/**/*.{ts,tsx}',
  ],
};

export default config;
