import { fieldTypeRegistry } from '@packages/field-types';
import type { FieldDefinition, PicklistOption, EntityRelationship } from '../types';

export interface ValidationError {
  field: string;
  message: string;
  code: 'required' | 'type' | 'maxLength' | 'format' | 'picklist' | 'readonly' | 'unknown' | 'auto_number';
}

export interface ValidationOptions {
  /** When true, required fields not present in payload are skipped (for partial updates) */
  partial?: boolean;
}

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
}

/** A field definition with its picklist options attached */
export type FieldDefinitionWithOptions = FieldDefinition & { picklistOptions: PicklistOption[] };

/**
 * Validate a flat entity payload against field definitions.
 * Pure synchronous function — async checks (uniqueness) remain in the entity service.
 *
 * Declared relationship names (e.g. `credentials`, `roles`) are accepted as
 * valid keys here — their shape is validated by each relationship's handler
 * inside the write-path transaction, not by the generic field validator.
 */
export function validatePayload(
  definitions: FieldDefinitionWithOptions[],
  payload: Record<string, unknown>,
  options?: ValidationOptions,
  relationships: EntityRelationship[] = [],
): ValidationResult {
  const errors: ValidationError[] = [];
  const defMap = new Map(definitions.map(d => [d.fieldKey, d]));
  const relNames = new Set(relationships.map(r => r.name));
  const partial = options?.partial ?? false;

  // Check for unknown keys in payload
  for (const key of Object.keys(payload)) {
    if (!defMap.has(key) && !relNames.has(key)) {
      errors.push({ field: key, message: `Unknown field '${key}'`, code: 'unknown' });
    }
  }

  for (const def of definitions) {
    const value = payload[def.fieldKey];
    const present = def.fieldKey in payload;

    // Auto-generated fields cannot be set by user
    const ft = fieldTypeRegistry.get(def.fieldType);
    if (ft?.autoGenerated && present) {
      errors.push({ field: def.fieldKey, message: 'Auto-number fields cannot be set manually', code: 'auto_number' });
      continue;
    }

    // Readonly fields cannot be set on update
    if (def.isReadonly && present && partial) {
      errors.push({ field: def.fieldKey, message: `Field '${def.label}' is read-only`, code: 'readonly' });
      continue;
    }

    // Skip readonly fields on create — they are auto-populated by the engine
    // (e.g. createdBy is set from actorId, createdAt/updatedAt from DB defaults)
    if (def.isReadonly && !present && !partial) {
      continue;
    }

    // Skip workflow fields on create — initial state is resolved by the workflow
    // registry and pipeline resolver after the row is inserted
    if (def.fieldType === 'workflow' && !present && !partial) {
      continue;
    }

    // Required check (skip in partial mode if field not present)
    if (def.isRequired && !partial) {
      if (!present || value === null || value === undefined || value === '') {
        errors.push({ field: def.fieldKey, message: `${def.label} is required`, code: 'required' });
        continue;
      }
    }

    // Skip validation if value not present or null (optional field)
    if (!present || value === null || value === undefined || value === '') {
      continue;
    }

    // Type and format validation via field type registry
    const fieldError = ft?.validate(value, {
      label: def.label,
      maxLength: def.maxLength,
      picklistOptions: def.picklistOptions,
    });
    if (fieldError) {
      errors.push({ field: def.fieldKey, ...fieldError });
    }
  }

  return { valid: errors.length === 0, errors };
}
