/**
 * Template functions for `gen:entity`. Each function takes the analyzed
 * entity context and returns the file contents as a string.
 *
 * Templates are plain TS template literals — no EJS dependency. New
 * templates can be added by writing another function here and wiring it
 * into the FILE_PLAN in generator.ts.
 */

import type { GeneratorContext } from './generator';

const HEADER = (entity: string, file: string) =>
  `// ============================================================================
// AUTO-GENERATED by \`pnpm gen:entity ${entity}\`. Do not edit by hand.
// Customizations belong in ${file}.
// ============================================================================`;

// -----------------------------------------------------------------------------
// dto.generated.ts — pure derivation from Drizzle schema + fieldMeta features
// -----------------------------------------------------------------------------

export function dtoGeneratedTemplate(ctx: GeneratorContext): string {
  const { entitySlug, singularPascal, tableIdent } = ctx;
  const featureLines = ctx.tagFields.map(
    (f) => `  ${f.key}: z.array(z.string().uuid()).optional(),`,
  );
  const featureBlock = featureLines.length > 0
    ? `\nconst FeatureFields = z.object({\n${featureLines.join('\n')}\n});\n\nexport const GeneratedCreate${singularPascal}Schema = RowFields.merge(FeatureFields);`
    : `\nexport const GeneratedCreate${singularPascal}Schema = RowFields;`;

  return `import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import { z } from 'zod';
import { ${tableIdent} } from './schema/${tableIdent}';

${HEADER(entitySlug, `${entitySlug}.dto.ts`)}

export const Generated${singularPascal}RowSchema = createSelectSchema(${tableIdent});

const RowFields = createInsertSchema(${tableIdent}).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
  deletedBy: true,
  createdBy: true,
});
${featureBlock}
export const GeneratedUpdate${singularPascal}Schema = GeneratedCreate${singularPascal}Schema.partial();
`;
}

// -----------------------------------------------------------------------------
// dto.ts — user-owned wrapper. Stubbed for first-time scaffold; never overwritten.
// -----------------------------------------------------------------------------

export function dtoTemplate(ctx: GeneratorContext): string {
  const { singularPascal } = ctx;
  return `import { z } from 'zod';
import {
  Generated${singularPascal}RowSchema,
  GeneratedCreate${singularPascal}Schema,
} from './${ctx.entitySlug}.dto.generated';

// User-owned. Add field-level validators, \`.refine()\` cross-field rules,
// and custom transforms here. The generator will not overwrite this file.

export const Create${singularPascal}Schema = GeneratedCreate${singularPascal}Schema;
export const Update${singularPascal}Schema = Create${singularPascal}Schema.partial();
export const ${singularPascal}RowSchema = Generated${singularPascal}RowSchema;

export type Create${singularPascal}Dto = z.infer<typeof Create${singularPascal}Schema>;
export type Update${singularPascal}Dto = z.infer<typeof Update${singularPascal}Schema>;
export type ${singularPascal}Row = z.infer<typeof ${singularPascal}RowSchema>;
`;
}

// -----------------------------------------------------------------------------
// service.ts — explicit composition. Scaffold-only.
// -----------------------------------------------------------------------------

export function serviceTemplate(ctx: GeneratorContext): string {
  const { entitySlug, singularPascal, pluralPascal } = ctx;
  const constLines: string[] = [`const ENTITY_TYPE = '${entitySlug}';`];
  const ctorParams: string[] = [
    `@Inject('ENTITY_SERVICE_${entitySlug}') private readonly entities: EntityService,`,
    `private readonly database: DatabaseService,`,
  ];
  const imports: string[] = [
    `import { Inject, Injectable } from '@nestjs/common';`,
    `import { DatabaseService } from '@packages/database';`,
    `import { EntityService, type BaseListQuery } from '@packages/entity-engine';`,
    `import type { DataAccessContext } from '@packages/rbac';`,
  ];

  if (ctx.tagFields.length > 0) {
    imports.push(`import { TaxonomyService } from '@packages/taxonomy';`);
    ctorParams.push(`private readonly taxonomy: TaxonomyService,`);
    for (const f of ctx.tagFields) {
      const upper = f.key.replace(/[a-z]+/g, (s) => s.toUpperCase());
      constLines.push(
        `const ${upper}_TAG_GROUP_SLUG = '${f.tagGroupSlug ?? `${entitySlug}-${f.key}`}';`,
      );
    }
  }

  imports.push(
    `import type { Create${singularPascal}Dto, Update${singularPascal}Dto } from './${entitySlug}.dto';`,
  );

  // Build create/update tag composition lines
  const tagCreateLines = ctx.tagFields.map((f) => {
    const upper = f.key.replace(/[a-z]+/g, (s) => s.toUpperCase());
    return `      if (${f.key}?.length) {
        await this.taxonomy.setTagsForEntityInGroup(
          ENTITY_TYPE, created.id as string, ${upper}_TAG_GROUP_SLUG, ${f.key}, tx,
        );
      }`;
  });
  const tagUpdateLines = ctx.tagFields.map((f) => {
    const upper = f.key.replace(/[a-z]+/g, (s) => s.toUpperCase());
    return `      if (${f.key} !== undefined) {
        await this.taxonomy.setTagsForEntityInGroup(
          ENTITY_TYPE, id, ${upper}_TAG_GROUP_SLUG, ${f.key}, tx,
        );
      }`;
  });

  const destructured = ctx.tagFields.length > 0
    ? `{ ${ctx.tagFields.map((f) => f.key).join(', ')}, ...row }`
    : 'row';

  return `${imports.join('\n')}

${constLines.join('\n')}

@Injectable()
export class ${pluralPascal}Service {
  constructor(
    ${ctorParams.join('\n    ')}
  ) {}

  list(query: BaseListQuery, accessCtx?: DataAccessContext) {
    return this.entities.list(query, accessCtx);
  }

  findOne(id: string, accessCtx?: DataAccessContext) {
    return this.entities.findOneOrFail(id, accessCtx);
  }

  async create(input: Create${singularPascal}Dto, actorId: string) {
    const ${destructured} = input;

    return this.database.db.transaction(async (tx) => {
      const created = await this.entities.create(row, actorId, tx);
${tagCreateLines.join('\n')}
      return created;
    });
  }

  async update(
    id: string,
    input: Update${singularPascal}Dto,
    actorId: string,
    accessCtx?: DataAccessContext,
  ) {
    const ${destructured} = input;

    return this.database.db.transaction(async (tx) => {
      const updated = await this.entities.update(id, row, actorId, accessCtx, tx);
${tagUpdateLines.join('\n')}
      return updated;
    });
  }

  softDelete(id: string, actorId: string, accessCtx?: DataAccessContext) {
    return this.entities.softDelete(id, actorId, accessCtx);
  }

  clone(id: string, actorId: string) {
    return this.entities.clone(id, actorId);
  }

  restore(id: string) {
    return this.entities.restore(id);
  }

  getListLayout() {
    return this.entities.getListLayout();
  }
}
`;
}

// -----------------------------------------------------------------------------
// controller.ts — RBAC + Zod parse pass-through. Scaffold-only.
// -----------------------------------------------------------------------------

export function controllerTemplate(ctx: GeneratorContext): string {
  const { entitySlug, singularPascal, pluralPascal } = ctx;
  return `import {
  Body, Controller, Delete, Get, HttpCode, HttpStatus,
  Param, ParseUUIDPipe, Patch, Post, Query,
} from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';
import { CurrentUser, type JwtPayload } from '@packages/auth';
import { AccessContext, RequirePermission, type DataAccessContext } from '@packages/rbac';
import { ${pluralPascal}Service } from './${entitySlug}.service';
import { Create${singularPascal}Schema, Update${singularPascal}Schema } from './${entitySlug}.dto';

@ApiTags('${entitySlug}')
@Controller('${entitySlug}')
export class ${pluralPascal}Controller {
  constructor(private readonly ${entitySlug}: ${pluralPascal}Service) {}

  @Get('layout/list')
  @RequirePermission('${entitySlug}.read')
  getListLayout() {
    return this.${entitySlug}.getListLayout();
  }

  @Get()
  @RequirePermission('${entitySlug}.read')
  list(@Query() query: Record<string, unknown>, @AccessContext() accessCtx?: DataAccessContext) {
    const parsed = {
      ...query,
      page: query.page ? Number(query.page) : undefined,
      limit: query.limit ? Number(query.limit) : undefined,
      includeDeleted: query.includeDeleted === 'true',
    };
    return this.${entitySlug}.list(parsed, accessCtx);
  }

  @Get(':id')
  @RequirePermission('${entitySlug}.read')
  findOne(@Param('id', ParseUUIDPipe) id: string, @AccessContext() accessCtx?: DataAccessContext) {
    return this.${entitySlug}.findOne(id, accessCtx);
  }

  @Post()
  @RequirePermission('${entitySlug}.create')
  @HttpCode(HttpStatus.CREATED)
  create(@Body() body: unknown, @CurrentUser() user: JwtPayload) {
    const input = Create${singularPascal}Schema.parse(body);
    return this.${entitySlug}.create(input, user.userId);
  }

  @Patch(':id')
  @RequirePermission('${entitySlug}.update')
  update(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() body: unknown,
    @CurrentUser() user: JwtPayload,
    @AccessContext() accessCtx?: DataAccessContext,
  ) {
    const input = Update${singularPascal}Schema.parse(body);
    return this.${entitySlug}.update(id, input, user.userId, accessCtx);
  }

  @Delete(':id')
  @RequirePermission('${entitySlug}.delete')
  @HttpCode(HttpStatus.NO_CONTENT)
  async delete(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @AccessContext() accessCtx?: DataAccessContext,
  ) {
    await this.${entitySlug}.softDelete(id, user.userId, accessCtx);
  }
}
`;
}

// -----------------------------------------------------------------------------
// module.ts — regenerable DI wiring.
// -----------------------------------------------------------------------------

export function moduleTemplate(ctx: GeneratorContext): string {
  const { entitySlug, pluralPascal, configIdent } = ctx;
  return `import { Module } from '@nestjs/common';
import { EntityEngineModule } from '@packages/entity-engine';
import { ${configIdent} } from './${entitySlug}.config';
import { ${pluralPascal}Controller } from './${entitySlug}.controller';
import { ${pluralPascal}Service } from './${entitySlug}.service';

${HEADER(entitySlug, `${entitySlug}.service.ts (composition) or ${entitySlug}.controller.ts (routes)`)}

@Module({
  imports: [EntityEngineModule.forEntity(${configIdent})],
  controllers: [${pluralPascal}Controller],
  providers: [${pluralPascal}Service],
  exports: [${pluralPascal}Service],
})
export class ${pluralPascal}Module {}
`;
}

// -----------------------------------------------------------------------------
// permissions.ts — regenerable RBAC manifest.
// -----------------------------------------------------------------------------

export function permissionsTemplate(ctx: GeneratorContext): string {
  const { entitySlug } = ctx;
  return `${HEADER(entitySlug, 'the entity config (custom permissions go on actions[].permission)')}

export const ${entitySlug.toUpperCase()}_PERMISSIONS = [
  { slug: '${entitySlug}.read',   module: '${entitySlug}', action: 'read',   label: 'View ${entitySlug}',   description: 'View ${entitySlug} records', supportedScopes: ['any', 'creator'] },
  { slug: '${entitySlug}.create', module: '${entitySlug}', action: 'create', label: 'Create ${entitySlug}', description: 'Create new ${entitySlug}',   supportedScopes: ['any'] },
  { slug: '${entitySlug}.update', module: '${entitySlug}', action: 'update', label: 'Update ${entitySlug}', description: 'Update ${entitySlug} records', supportedScopes: ['any', 'creator'] },
  { slug: '${entitySlug}.delete', module: '${entitySlug}', action: 'delete', label: 'Delete ${entitySlug}', description: 'Delete ${entitySlug} records', supportedScopes: ['any', 'creator'] },
] as const;
`;
}

// -----------------------------------------------------------------------------
// index.ts — regenerable barrel.
// -----------------------------------------------------------------------------

export function indexTemplate(ctx: GeneratorContext): string {
  const { entitySlug, pluralPascal } = ctx;
  return `${HEADER(entitySlug, '(none — this is a pure barrel)')}

export { ${pluralPascal}Module } from './${entitySlug}.module';
export { ${pluralPascal}Service } from './${entitySlug}.service';
`;
}
