import type { FieldTypeDefinition, FieldTypeFamily } from './types';
import * as validators from './validators';

// ---------------------------------------------------------------------------
// Family defaults — each family provides sensible base values so that
// individual field type definitions only need to specify what is different.
// UI concerns (FormComponent, ViewComponent, etc.) are NOT included here.
// They are added separately in the ui/ layer.
// ---------------------------------------------------------------------------

type FamilyDefaults = Omit<FieldTypeDefinition, 'type' | 'label' | 'icon' | 'color' | 'sortOrder'>;

const FAMILY_DEFAULTS: Record<FieldTypeFamily, FamilyDefaults> = {
  text: {
    family: 'text',
    storage: { type: 'eav', column: 'valueText' },
    validate: validators.string,
    filterOperators: ['eq', 'neq', 'like', 'isNull', 'isNotNull'],
    filterable: true,
    excludeFromList: false,
    sortable: true,
    autoGenerated: false,
    isArray: false,
    isReference: false,
    creatable: true,
  },

  numeric: {
    family: 'numeric',
    storage: { type: 'eav', column: 'valueNumber' },
    validate: validators.integer,
    filterOperators: ['eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'between', 'isNull', 'isNotNull'],
    filterable: true,
    excludeFromList: false,
    sortable: true,
    autoGenerated: false,
    isArray: false,
    isReference: false,
    creatable: true,
  },

  date: {
    family: 'date',
    storage: { type: 'eav', column: 'valueDate' },
    validate: validators.date,
    filterOperators: ['eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'between', 'isNull', 'isNotNull'],
    filterable: true,
    excludeFromList: false,
    sortable: true,
    autoGenerated: false,
    isArray: false,
    isReference: false,
    creatable: true,
  },

  reference: {
    family: 'reference',
    storage: { type: 'eav', column: 'valueText' },
    validate: validators.uuid,
    filterOperators: ['eq', 'neq', 'in', 'isNull', 'isNotNull'],
    filterable: true,
    excludeFromList: false,
    sortable: true,
    autoGenerated: false,
    isArray: false,
    isReference: true,
    creatable: true,
  },

  selection: {
    family: 'selection',
    storage: { type: 'eav', column: 'valueText' },
    validate: validators.picklist,
    filterOperators: ['eq', 'neq', 'in', 'isNull', 'isNotNull'],
    filterable: true,
    excludeFromList: false,
    sortable: true,
    autoGenerated: false,
    isArray: false,
    isReference: false,
    creatable: true,
  },

  taxonomy: {
    family: 'taxonomy',
    storage: { type: 'relational', through: 'tags' },
    validate: validators.uuidArray,
    filterOperators: ['contains', 'isNull', 'isNotNull'],
    filterable: true,
    excludeFromList: false,
    sortable: false,
    autoGenerated: false,
    isArray: true,
    isReference: false,
    creatable: true,
  },

  special: {
    family: 'special',
    storage: { type: 'eav', column: 'valueText' },
    validate: validators.noop,
    filterOperators: ['eq', 'isNull'],
    filterable: false,
    excludeFromList: true,
    sortable: false,
    autoGenerated: false,
    isArray: false,
    isReference: false,
    creatable: false,
  },
};

// ---------------------------------------------------------------------------
// defineFieldType() — merges family defaults with per-type overrides
// ---------------------------------------------------------------------------

type RequiredFields = Pick<FieldTypeDefinition, 'type' | 'label' | 'family' | 'icon' | 'color' | 'sortOrder'>;
type OptionalOverrides = Partial<Omit<FieldTypeDefinition, keyof RequiredFields>>;

export function defineFieldType(
  partial: RequiredFields & OptionalOverrides,
): FieldTypeDefinition {
  const familyDefaults = FAMILY_DEFAULTS[partial.family];
  return {
    ...familyDefaults,
    ...partial,
  };
}
