// ---------------------------------------------------------------------------
// Storage strategy — declares how a field type persists its data
// ---------------------------------------------------------------------------

export type EavValueColumn = 'valueText' | 'valueNumber' | 'valueDate' | 'valueDatetime' | 'valueBoolean';

export type StorageStrategy =
  | { type: 'eav'; column: EavValueColumn }
  | { type: 'json'; column: EavValueColumn }         // JSON array stored in EAV text column (multi_select)
  | { type: 'relational'; through: 'multiValues' }   // entity_multi_values junction table
  | { type: 'relational'; through: 'tags' }           // entity_tags junction table
  | { type: 'column' }                                // direct table column (standard fields)
  | { type: 'composite' };                            // one logical field spans multiple typed columns (e.g. address)

// ---------------------------------------------------------------------------
// Filter operators
// ---------------------------------------------------------------------------

export type FilterOperator =
  | 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte'
  | 'like' | 'in' | 'notIn' | 'isNull' | 'isNotNull'
  | 'between' | 'contains';

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export interface FieldValidationContext {
  label: string;
  maxLength?: number | null;
  picklistOptions?: { value: string }[];
  isRequired?: boolean;
}

export interface FieldValidationError {
  message: string;
  code: 'required' | 'type' | 'maxLength' | 'format' | 'picklist' | 'readonly' | 'unknown' | 'auto_number';
}

export type ValidateFn = (
  value: unknown,
  ctx: FieldValidationContext,
) => FieldValidationError | null;

// ---------------------------------------------------------------------------
// Field type family — drives defaults in defineFieldType()
// ---------------------------------------------------------------------------

export type FieldTypeFamily = 'text' | 'numeric' | 'date' | 'reference' | 'selection' | 'taxonomy' | 'special';

// ---------------------------------------------------------------------------
// Field type definition — the complete description of a field type
// ---------------------------------------------------------------------------

export interface FieldTypeDefinition {
  // --- Identity ---
  type: string;
  label: string;
  family: FieldTypeFamily;

  // --- Admin palette ---
  icon: string;
  color: string;
  creatable: boolean;
  sortOrder: number;

  // --- Storage ---
  storage: StorageStrategy;

  // --- Backend validation ---
  validate: ValidateFn;

  // --- Filtering ---
  filterOperators: FilterOperator[];
  filterable: boolean;

  // --- List view behavior ---
  excludeFromList: boolean;
  sortable: boolean;

  // --- Behavior flags ---
  autoGenerated: boolean;
  isArray: boolean;
  isReference: boolean;
  defaultLookupEntity?: string;
}

// ---------------------------------------------------------------------------
// Plugin — a named group of field types registered by a package
// ---------------------------------------------------------------------------

export interface FieldTypePlugin {
  name: string;
  fieldTypes: FieldTypeDefinition[];
}
