import { fieldTypeRegistry } from '@packages/field-types';
import type { FieldDefinition } from '../types';

/**
 * Build a clean payload for cloning an entity.
 *
 * Given a hydrated source record and its field definitions, produces a payload
 * suitable for passing to EntityService.create():
 * - Skips auto_number, workflow, and readonly fields
 * - Transforms relational fields (tags, multi_user, multi_lookup) from hydrated
 *   [{id, ...}] format back to string[] of IDs
 * - Prefixes the primary name field with "Copy of "
 */
export function buildClonePayload(
  source: Record<string, unknown>,
  defs: FieldDefinition[],
  primaryNameField: string,
): Record<string, unknown> {
  const payload: Record<string, unknown> = {};

  for (const def of defs) {
    // Skip auto-generated, readonly, and workflow fields
    const ft = fieldTypeRegistry.get(def.fieldType);
    if (ft?.autoGenerated) continue;
    if (def.isReadonly) continue;
    if (def.fieldType === 'workflow') continue;

    const value = source[def.fieldKey];
    if (value === undefined || value === null) continue;

    // Transform relational fields from hydrated format back to IDs
    if (def.fieldType === 'tags') {
      if (Array.isArray(value)) {
        payload[def.fieldKey] = value.map((t: any) => t.id);
      }
      continue;
    }

    if (def.fieldType === 'multi_user' || def.fieldType === 'multi_lookup') {
      if (Array.isArray(value)) {
        payload[def.fieldKey] = value.map((v: any) => v.id);
      }
      continue;
    }

    // Prefix "Copy of" to the primary name field
    if (def.fieldKey === primaryNameField && typeof value === 'string') {
      payload[def.fieldKey] = `Copy of ${value}`;
      continue;
    }

    payload[def.fieldKey] = value;
  }

  return payload;
}
